# Generated by Django 4.1.4 on 2022-12-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='films/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('premier_year', models.SmallIntegerField()),
                ('type', models.CharField(max_length=250)),
            ],
        ),
    ]
