# Generated by Django 4.1.4 on 2022-12-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
