# Generated by Django 4.1.4 on 2022-12-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_film_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='age_rating',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
